services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb-vol:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    expose:
      - "9000"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress-vol:/usr/www

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress-vol:/usr/share/webapps

networks:
  inception:
    driver: bridge

volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ahmad/data/wordpress
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ahmad/data/mysql
