CREATE DATABASE IF NOT EXISTS ${DB_NAME};

CREATE USER IF NOT EXISTS 'healthcheck'@'localhost';
CREATE USER IF NOT EXISTS '${WP_USER}'@'%'
    IDENTIFIED BY '${WP_PASS}';

GRANT ALL PRIVILEGES
    ON ${DB_NAME}.*
    TO '${WP_USER}'@'%';
