CREATE DATABASE IF NOT EXISTS ${DB_NAME};

CREATE USER IF NOT EXISTS '${WP_USER}'@'%'
    IDENTIFIED BY '${WP_PASS}';

CREATE USER IF NOT EXISTS '${WP_ADMIN}'@'%'
    IDENTIFIED BY '${WP_ADMIN_PASS}';

GRANT ALL PRIVILEGES
    ON ${DB_NAME}.*
    TO '${WP_USER}'@'%';

GRANT ALL PRIVILEGES
    ON ${DB_NAME}.*
    TO '${WP_ADMIN}'@'%';
